# Generated by Django 3.2.6 on 2021-09-04 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(upload_to='images/')),
                ('no_of_questions', models.IntegerField()),
                ('total_mark', models.IntegerField()),
                ('pass_mark', models.IntegerField(default=0)),
                ('api', models.CharField(max_length=450)),
            ],
        ),
    ]
